/**********************************************************************************************/
/*  This program is part of the Barcelona OpenMP Tasks Suite                                  */
/*  Copyright (C) 2009 Barcelona Supercomputing Center - Centro Nacional de Supercomputacion  */
/*  Copyright (C) 2009 Universitat Politecnica de Catalunya                                   */
/*                                                                                            */
/*  This program is free software; you can redistribute it and/or modify                      */
/*  it under the terms of the GNU General Public License as published by                      */
/*  the Free Software Foundation; either version 2 of the License, or                         */
/*  (at your option) any later version.                                                       */
/*                                                                                            */
/*  This program is distributed in the hope that it will be useful,                           */
/*  but WITHOUT ANY WARRANTY; without even the implied warranty of                            */
/*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the                             */
/*  GNU General Public License for more details.                                              */
/*                                                                                            */
/*  You should have received a copy of the GNU General Public License                         */
/*  along with this program; if not, write to the Free Software                               */
/*  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA            */
/**********************************************************************************************/

/* Original code from the Application Kernel Matrix by Cray */

char *amino_acid_order = "ABCDEFGHIKLMNPQRSTVWXYZ";
char *amino_acid_codes = "ABCDEFGHIKLMNPQRSTUVWXYZ-";

int gon250mt[]={
  24,
   0,   0,
   5,   0, 115,
  -3,   0, -32,  47,
   0,   0, -30,  27,  36,
 -23,   0,  -8, -45, -39,  70,
   5,   0, -20,   1,  -8, -52,  66,
  -8,   0, -13,   4,   4,  -1, -14,  60,
  -8,   0, -11, -38, -27,  10, -45, -22,  40,
  -4,   0, -28,   5,  12, -33, -11,   6, -21,  32,
 -12,   0, -15, -40, -28,  20, -44, -19,  28, -21,  40,
  -7,   0,  -9, -30, -20,  16, -35, -13,  25, -14,  28,  43,
  -3,   0, -18,  22,   9, -31,   4,  12, -28,   8, -30, -22,  38,
   3,   0, -31,  -7,  -5, -38, -16, -11, -26,  -6, -23, -24,  -9,  76,
  -2,   0, -24,   9,  17, -26, -10,  12, -19,  15, -16, -10,   7,  -2,  27,
  -6,   0, -22,  -3,   4, -32, -10,   6, -24,  27, -22, -17,   3,  -9,  15,  47,
  11,   0,   1,   5,   2, -28,   4,  -2, -18,   1, -21, -14,   9,   4,   2,  -2,  22,
   6,   0,  -5,   0,  -1, -22, -11,  -3,  -6,   1, -13,  -6,   5,   1,   0,  -2,  15,  25,
   1,   0,   0, -29, -19,   1, -33, -20,  31, -17,  18,  16, -22, -18, -15, -20, -10,   0,  34,
 -36,   0, -10, -52, -43,  36, -40,  -8, -18, -35,  -7, -10, -36, -50, -27, -16, -33, -35, -26, 142,
   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
 -22,   0,  -5, -28, -27,  51, -40,  22,  -7, -21,   0,  -2, -14, -31, -17, -18, -19, -19, -11,  41,   0,  78,
   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0};


#define ALIGNMENT_DATA "Number of sequences is 20\
\
>gi|547089|gb|AAB30997.1| monocyte chemotactic protein-3; MCP-3; Marc/Fic protein [Mus sp.]=:A001486:mouse\
MRISATLLCLLLIAAAFSIQVWAQPDGPNASTCCYVKKQKIPKRNLKSYRRITSSRCPWEAVIFKTKKGMEV\
CAEAHQKWVEEAIAYLDMKTPTPKP\
>gi|20563279|gb|AAM27959.1| gp130-like monocyte receptor [Mus musculus]=:A002913:mouse\
MWTLALWAFSFLCKFSLAVLPTKPENISCVFYFDRNLTCTWRPEKETNDTSYIVTLTYSYGKSNYSDNATEA\
SYSFPRSCAMPPDICSVEVQAQNGDGKVKSDITYWHLISIAKTEPPIILSVNPICNRMFQIQWKPREKTRGF\
PLVCMLRFRTVNSSRWTEVNFENCKQVCNLTGLQAFTEYVLALRFRFNDSRYWSKWSKEETRVTMEEVPHVL\
DLWRILEPADMNGDRKVRLLWKKARGAPVLEKTFGYHIQYFAENSTNLTEINNITTQQYELLLMSQAHSVSV\
TSFNSLGKSQETILRIPDVHEKTFQYIKSMQAYIAEPLLVVNWQSSIPAVDTWIVEWLPEAAMSKFPALSWE\
SVSQVTNWTIEQDKLKPFTCYNISVYPVLGHRVGEPYSIQAYAKEGTPLKGPETRVENIGLRTATITWKEIP\
KSARNGFINNYTVFYQAEGGKELSKTVNSHALQCDLESLTRRTSYTVWVMASTRAGGTNGVRINFKTLSISV\
FEIVLLTSLVGGGLLLLSIKTVTFGLRKPNRLTPLCCPDVPNPAESSLATWLGDGFKKSNMKETGNSGNTED\
VVLKPCPVPADLIDKLVVNFENFLEVVLTEEAGKGQASILGGEANEYVTSPSRPDGPPGKSFKEPSILTEVA\
SEDSHSTCSRMADEAYSELARQPSSSCQSPGLSPPREDQAQNPYLKNSVTTREFLVHENIPEHSKGEV\
>gi|20982827|ref|NP_631877.1| EGF-like module containing, mucin-like, hormone receptor-like sequence 4; seven-span membrane protein FIRE; F4/80-like-receptor [Mus musculus]=:A003692:mouse\
MGSRCLLHASVPGMLLIWSILQMMNISASCPQCNENASCFNSTHCVCKEGFWTGSENRRIIEPHEKCQDINE\
CLLKELVCKDVSYCRNKIGTYICSCVVKYPLFNWVAGIINIDHPDCYVNKSKNTGSKTHTLGVLSEFKSKEE\
VAKGATKLLRKVEHHILNENSDIPKKDENPLLDIVYETKRCKTMTLLEAGNNTMKVDCTSGFKEHNSGGETA\
VAFIAYKSLGNLLNGSFFSNEEGFQEVTLNSHIVSGAIRSEVKPVLSEPVLLTLQNIQPIDSRAEHLCVHWE\
GSEEGGSWSTKGCSHVYTNNSYTICKCFHLSSFAVLMALPHEEDGVLSALSVITYVGLSLSLLCLFLAAITF\
LLCRPIQNTSTTLHLQLSICLFLADLLFLTGINRTKPKVLCSIIAGMLHYLYLASFMWMFLEGLHLFLTVSN\
LKVANYSNSGRFKKRFMYPVGYGLPAFIVAVSAIAGHKNYGTHNHCWLSLHRGFIWSFLGPAAAIILINLVF\
YFLIIWILRSKLSSLNKEVSTLQDTKVMTFKAIVQLFVLGCSWGIGLFIFIEVGKTVRLIVAYLFTIINVLQ\
GVLIFMVHCLLNRQVRMEYKKWFHRLRKEVESESTEVSHSTTHTKMGLSLNLENFCPTGNLHDPSDSILPST\
EVAGVYLSTPRSHMGAEDVNSGTHAYWSRTISD\
>gi|33348856|gb|AAC53517.2| TWEAK [Mus musculus]=:A003363:mouse\
MAARRSQRRRGRRGEPGTALLAPLVLSLGLALACLGLLLVVVSLGSWATLSAQEPSQEELTAEDRREPPELN\
PQTEESQDVVPFLEQLVRPRRSAPKGRKARPRRAIAAHYEVHPRPGQDGAQAGVDGTVSGWEETKINSSSPL\
RYDRQIGEFTVIRAGLYYLYCQVHFDEGKAVYLKLDLLVNGVLALRCLEEFSATAASSPGPQLRLCQVSGLL\
PLRPGSSLRIRTLPWAHLKAAPFLTYFGLFQVH\
>gi|3153816|gb|AAC40122.1| oncostatin M specific receptor [Mus musculus]=:A001697:mouse\
MAFSVVLHPAFLLAVLSLRASRSEVLEEPLPLTPEIHKVSFQLKLQEVNLEWTVPALTHEELNMIFQIEISR\
LNISNTIWVENYSTTVKREEAVRWNWTSDIPLECVKHFIRIRALVDDTKSLPQSSWGNWSSWKEVNAKVSVE\
PDKSLIFPKDKVLEEGSNVTICLMYGQNVYNVSCKLQDEPIHGEQLDSHVSLLKLNNVVFLSDTGTNINCQA\
TKGPKRIFGTVLFVSKVLEEPKNVSCETRDFKTLDCSWEPGVDTTLTWRKQRFQNYTLCESFSKRCEVSNYR\
NSYTWQITEGSQEMYNFTLTAENQLRKRSVNINFNLTHRVHPKAPQDVTLKIIGATKANMTWKVHSHGNNYT\
LLCQVKLQYGEVIHEHNVSVHMSANYLFSDLDPDTKYKAFVRCASANHFWKWSDWTQKEFSTPETAPSQALD\
VWRQVWSENGRRIVTLFWKPLLKSQANGKIISYNIVVENEAKPTESEHYCVWAPALSTNLSLDLQPYKIRIT\
TNNSMGASPESLMVLSNDSGHEEVKEKTIKGIKDAFNISWEPVSGDTMGYVVDWCAHSQDQRCDLQWKNLGP\
NTTSTTITSDDFKPGVRYNFRIFERSVEHKARLVEKQRGYTQELAPLVNPKVEIPYSTPNSFVLRWPDYDSD\
FQAGFIKGYLVYVKSKEMQCNQPWERTLLPDNSVLCKYDINGSETKTLTVENLQPESLYEFFVTPYTSAGPG\
PNETFTKVTTPDARSHMLLQIILPMTLCVLLSIIVCYWKSQWVKEKCYPDIPNPYKSSILSLIKSKKNPHLI\
MNVKDCIPDVLEVINKAEGSKTQCVGSGKLHIEDVPTKPPIVPTEKDSSGPVPCIFFENFTYDQSAFDSGSH\
GLIPGPLKDTAHQLGLLAPPNKFQNVLKNDYMKPLVESPTEETSLIYVSQLASPMCGDKDTLATEPPVPVHG\
SEYKRQMVVPGSLASPSLKEDNSLTSTVLLGQGEQ\
>gi|20521103|dbj|BAA25532.2| KIAA0606 protein [Homo sapiens]=:A003112:human\
SFSLSPSAESVSDRLDPYSSGGGSSSSSEELEADAASAPTGVPGQPRRPGHPAQPLPLPQTASSPQPQQKAP\
RAIDSPGGAVREGSCEEKAAAAVAPGGLQSTPGRSGVTAEKAPPPPPPPTLYVQLHGETTRRLEAEEKPLQI\
QNDYLFQLGFGELWRVQEEGMDSEIGCLIRFYAGKPHSTGSSERIQLSGMYNVRKGKMQLPVNRWTRRQVIL\
CGTCLIVSSVKDSLTGKMHVLPLIGGKVEEVKKHQHCLAFSSSGPQSQTYYICFDTFTEYLRWLRQVSKVAS\
QRISSVDLSCCSLEHLPANLFYSQDLTHLNLKQNFLRQNPSLPAARGLNELQRFTKLKSLNLSNNHLGDFPL\
AVCSIPTLAELNVSCNALRSVPAAVGVMHNLQTFLLDGNFLQSLPAELENMKQLSYLGLSFNEFTDIPEVLE\
KLTAVDKLCMSGNCVETLRLQALRKMPHIKHVDLRLNVIRKLIADEVDFLQHVTQLDLRDNKLGDLDAMIFN\
NIEVLHCERNQLVTLDICGYFLKALYASSNELVQLDVYPVPNYLSYMDVSRNRLENVPEWVCESRKLEVLDI\
GHNQICELPARLFCNSSLRKLLAGHNQLARLPERLERTSVEVLDVQHNQLLELPPNLLMKADSLRFLNASAN\
KLESLPPATLSEETNSILQELYLTNNSLTDKCVPLLTGHPHLKILHMAYNRLQSFPASKMAKLEELEEIDLS\
GNKLKAIPTTIMNCSRMHTVIAHSNCIEVFPEVMQLPEIKCVDLSCNELSEVTLPENLPPKLQELDLTGNPR\
LVLDHKTLELLNNIRCFKIDQPSTGDASGAPAVWSHGYTEASGVKNKLCVAALSVNNFCDNREALYGVFDGD\
RNVEVPYLLQCTMSDILAEELQKTKNEEEYMVNTFIVMQRKLGTAGQKLGGAAVLCHIKHDPVDPGGSFTLT\
SANVGKCQTVLCRNGKPLPLSRSYIMSCEEELKRIKQHKAIITEDGKVNGVTESTRILGYTFLHPSVVPRPH\
VQSVLLTPQDEFFILGSKGLWDSLSVEEAVEAVRNVPDALAAAKKLCTLAQSYGCHDSISAVVVQLSVTEDS\
FCCCELSAGGAVPPPSPGIFPPSVNMVIKDRPSDGLGVPSSSSGMASEISSELSTSEMSSEVGSTASDEPPP\
GALSENSPAYPSEQRCMLHPICLSNSFQRQLSSATFSSAFSDNGLDSDDEEPIEGVFTNGSRVEVEVDIHCS\
RAKEKEKQQHLLQVPAEASDEGIVISANEDEPGLPRKADFSAVGTIGRRRANGSVAPQERSHNVIEVATDAP\
LRKPGGYFAAPAQPDPDDQFIIPPELEEEVKEIMKHHQEQQQQQQPPPPPQLQPQLPRHYQLDQLPDYYDTP\
L\
>gi|27753998|ref|NP_083070.2| nudix (nucleoside diphosphate linked moiety X)-type motif 9 [Mus musculus]=:A003420:mouse\
MAGRSLGQAVATVSLSVALASVTVRSSACRAVPAPRNTFPTCGFHLNANIMSGSNGAKENSHNKARTSPYPG\
SKVERSQVPNEKVGWLVEWQDYNPVEYTAVSVLAGPQWADPQISESNFSPKFNEKDGHVERKSQNGLYEIEN\
GRPRNPAGRTGLVGRGLLGRWGPNHAADPIITRWKRDESGNKITHPVSGKCILQFVAIKRKDCGEWAIPGGM\
VDPGEKISATLKREFGEEALNSLQKSSAEKREIEEKLHALFSQEHLVIYKGYVDDPRNTDNAWMETEAVNYH\
DETGETMDNLTLEAGDDAGKVKWVDISDQLKLYASHSQFIKLVAEKRDAHWSEDHAADSRGL\
>gi|26340112|dbj|BAC33719.1| unnamed protein product [Mus musculus]=:A001588:mouse\
MAEQESLEFGKADFVLMDTVSMPEFMANLRLRFEKGRIYTFIGEVVVSVNPYKVLNIYGRDTVEQYKGRELY\
ERPPHLFAIADAAYKAMKRRSKDTCIMISGESGAGKTEASKYIMQYIAAITNPSQRAEIERVKNMLLKSNCV\
LEAFGNAKTNRNDNSSRFGKYMDINFDFKGDPIGGHINNYLLEKSRVIVQQPGERSFHSFYQLLQGGSEQML\
HSLHLQKSLSSYNYIRVGAQLKSSINDAAEFKVVADAMKVIGFKPEEIQTVYKILAVILHLGNLKFIVDGDT\
PLIENGKVVSVIAELLSTKADMVEKALLYRTVATGRDIIDKQHTEQEASYGRDAFAKAIYERLFCWIVTRIN\
DIIEVKNYDTTIHGKNTVIGVLDIYGFEIFDNNSFEQFCINYCNEKLQQLFIQLVLKQEQEEYQREGIPWKH\
IDYFNNQIIVDLVEQQHKGIIAILDDACMNVGKVTDGMFLEALNSKLGKHGHFSSRKTCASDKILEFDRDFR\
IRHYAGDVVYSAIGFIDKNKDTLFQDFKRLMYNSSNPVLKNMWPEGKLSITEVTKRPLTAATLFKNSMIALV\
DNLASKEPYYVRCIKPNDKKSPQIFDDERCRHQVEYLGLLENVRVRRAGFAFRQTYEKFLHRYKMISEFTWP\
NHDLPSDKEAVKKLIERCGFQDDVAYGKSKIFIRTPRTLFTLEELRAQMLVRVVLFLQKVWRGTLARMRYKR\
TKAALTIIRYYRRYKVKSYIHEVARRFHGVKNMRDYGKHVKWPTPPKVLRRFEEALQSIFNRWSIPTHQDHT\
CIRPSPGQGKGCSHGDAERSKGRPWTPESLGRQLSCFEARHTSDLRHFRPSC\
>gi|19311014|ref|NP_597844.1| PKC-potentiated PP1 inhibitory protein [Mus musculus]=:A003079:mouse\
MSVVTGGGEAAGGGGGGGARVFFQSPRGGTGGSPGSSSSSGSSREDSAPVTTVAAAGQVQQQQRRHQQGKVT\
VKYDRKELRKRLVLEEWIVEQLGQLYGCEEEEMPDVEIDIDDLLDANSEEERASKLQEALVDCYKPTEEFIR\
ELLSRIRGMRKLSPPQKKSV\
>gi|18141131|gb|AAL60516.1| SH2 domain containing SOCS box protein SOCS7 [Mus musculus]=:A002191:mouse\
MVFRNVGRPPEEEDAEAAREPGPSELLCPRHRCALDPKALPPGLALERTWGPVAGLEAQLAALGLGQPAGPG\
IKTAGGGCCPCPCPPQPPPPQPPPPAAAPQAGEDPTETSDALLVLEGLESEAESLETNSCSEEELSSPGRGG\
GGVGGRLLLQPPGPELPPVPFPLQDLVPPGRLSRGEQQQQQPPPPPPPPGPLRPLAGPSRKGSFKIRLSRLF\
RTKSCNGGSGGGDGTGKRPSGDLAASAASLTDMGGSAVRELDTGRKPRLTRTQSAFSPVSFSPLFTGETVSL\
VDVDISQRGLTSPHPPTPPPPPRRSLSLLDDISGTLPTSVLVAPMGSSLQSFPLPPPPPPHAPDAFPRIAPI\
RASESLHSQPPQHLQCPLYRPDSSSFAASLRELEKCGWYWGPMNWEDAEMKLKGKPDGSFLVRDSSDPRYIL\
SLSFRSQGITHHTRMEHYRGTFSLWCHPKFEDRCQSVVEFIKRAIMHSKNGKFLYFLRSRVPGLPPTPVQLL\
YPVSRFSNVKSLQHLCRFRIRQLVRIDHIPDLPLPKPLISYIRKFYYYDPQEEVYLSLKEAQLISKQKQEVE\
PST\
>gi|6678471|ref|NP_033475.1| tubulin, alpha 7; tubulin alpha 7 [Mus musculus]=:A002340:mouse\
MRECISIHVGQAGVQIGNACWELYCLEHGIQPDGQMPSDKTIGGGDDSFNTFFSETGAGKHVPRAVFVDLEP\
TVVDEVRTGTYRQLFHPEQLITGKEDAANNYARGHYTIGKEIVDLVLDRIRKLADLCTGLQGFLIFHSFGGG\
TGSGFASLLMERLSVDYGKKSKLEFAIYPAPQVSTAVVEPYNSILTTHTTLEHSDCAFMVDNEAIYDICRRN\
LDIERPTYTNLNRLIGQIVSSITASLRFDGALNVDLTEFQTNLVPYPRIHFPLATYAPVISAEKAYHEQLSV\
AEITNACFEPANQMVKCDPRHGKYMACCMLYRGDVVPKDVNAAIATIKTKRTIQFVDWCPTGFKVGINYQPP\
TVVPGGDLAKVQRAVCMLSNTTAIAEAWARLDHKFDLMYAKRAFVHWYVGEGMEEGEFSEAREDLAALEKDY\
EEVGVDSVEAEAEEGEEY\
>gi|9790167|ref|NP_062650.1| phospholipase C, delta; phospholipase C delta-1; PLC-delta 1 [Mus musculus]=:A001807:mouse\
MDSGRDFLTLHGLQDDPDLQALLKGSQLLKVKSSSWRRERFYKLQEDCKTIWQESRKVMRSPESQLFSIEDI\
QEVRMGHRTEGLEKFARDIPEDRCFSIVFKDQRNTLDLIAPSPADVQHWVQGLRKIIDRSGSMDQRQKLQHW\
IHSCLRKADKNKDNKMNFKEVKDFLKELNVQVDDSYARKIFRECDHSQTDSLEDEEIETFYRMLTQRAEIDR\
AFAEAAGSAETLSVEKLVTFLQHQQREEEAGPALALSLIERYEPSETAKAQRQMTKDGFLMYLLSADGNAFS\
LAHRRVYQDMNQPLSHYLVSSSHNTYLLEDQLTGPSSTEAYIRALCKGCRCLELDCWDGPNQEPIIYHGYTF\
TSKILFCDVLRAIRDYAFKASPYPVILSLENHCSLEQQRVMAHHLRAILGPMLLDQPLDGVTTSLPSPEQLK\
EKILLKGKKLGGLLPAGGENGPEATDVSDEDEAAEMEDEAVRSQVQHKPKEDKLKLVPELSDMVIYCKSVHF\
GGFSSPSTSGQAFYEMASFSESRALRLLQESGNSFVRHNVGHLSRIYPAGWRTDSSNYSPVEMWNGGCQIVA\
LNFQTPGPEMDVYLGCFQDNGGCGYVLKPAFLRDPDTTFNSRALTQGPWWAPKKLRVWIISGQQLPKVNKNK\
NSIVDPKVIVEIHGVGQDVASRQTAVITNNGFNPRWDTEFEFVVAVPDLALVRFMVEDYDSSSKNDFIGQST\
IPWNSLKQGYRHVHLLSKNGDLHPSATLFVKISIQD\
>gi|31543234|ref|NP_071295.2| mitogen activated protein kinase kinase kinase 11; mixed lineage kinase 3 [Mus musculus]=:A001551:mouse\
MEPLKNLFLKSPLGSWNGSGSGGGGGTGGVRPEGSPKATAAYANPVWTALFDYEPNGQDELALRKGDRVEVL\
SRDAAISGDEGWWAGQVGGQVGIFPSNYVSRGGGPPPCEVASFQELRLEEVIGIGGFGKVYRGSWRGELVAV\
KAARQDPDEDISVTAESVRQEARLFAMLAHPNIIALKAVCLEEPNLCLVMEYAAGGPLSRALAGRRVPPHVL\
VNWAVQIARGMHYLHCEALVPVIHRDLKSNNILLLQPIEGDDMEHKTLKITDFGLAREWHKTTQMSAAGTYA\
WMAPEVIKASTFSKGSDVWSFGVLLWELLTGEVPYRGIDCLAVAYGVAVNKLTLPIPSTCPEPFAQLMADCW\
AQDPHRRPDFASILQQLEALEAQVLREMPRDSFHSMQEGWKREIQGLFDELRAKEKELLSREEELTRAAREQ\
RSQAEQLRRREHLLAQWELEVFERELTLLLQQVDRERPHVRRRRGTFKRSKLRARDGGERISMPLDFKHRIT\
VQASPGLDRRRNVFEVGAGDSPTFPRFRAIQLEPTESGQTWGRQSPRRLEDSSNGERRACWAWGPSSPKPGE\
AQNGRRRSRMDEATWYLDSDDSSPLGSPSTPPALNGNPPRPSPEPEEPRRAGPTERGNSSGTPKLIQRALLR\
GTALLASLGLGRDLQPPGGLSRERGESPTAPPPAQMPSPCPPELPSTPLIRLSQTTPDAHSSPTPGPLLLDL\
GVPSGQPSAKSPRREETRGRTVSPPPGISRSAPGTPGTPRSPPLGLISRPRPSPLRSRIDPWSFVSAGPRPS\
PLPSPQPAPRRAPWTLFPDSDPFWDSPPANPFRGGSQDCRTQTKDMGAQAPWAPEAGP\
>gi|6678475|ref|NP_033479.1| U2 small nuclear ribonucleoprotein auxiliary factor (U2AF) 1, related sequence 2; U2 small nuclear ribonucleoprotein auxiliary factor (U2AF), 35 kDa, related sequence 2 [Mus musculus]=:A003283:mouse\
METAGATADATAGPQKLSRKKYLALRKKERRKRRRQALARLREAELAQKEEEEDPLAEEKRLEEERLLEEER\
QRLHEEWLLREEKAQEEFRAKKKKEEEARKRKEELERKLKAEWEEQQRKEREEEEQKRQEKREREEAVQKML\
DQAENELENGGTWQNPEPPMDIRVLEKDRANCPFYSKTGACRFGDRCSRKHNFPTSSPTLLIKGMFTTFGME\
QCRRDDYDPDSSLEFSEEEIYQQFLDFYYDVLPEFKSVGKVIQFKVSCNLEPHLRGNVYVQYQSEEDCQAAF\
SVFNGRWYAGRQLQCEFCPVTRWKMAICGLFEVQQCPRGKHCNFLHVFRNPNNEYRDANRDLYPSPDWTSSS\
FGKNSERRERASHYDEYYGRSRRRRRSPSPDFYKRNGESDRKSSSRHRVKKSHRYGMKSRERRSSPSRRRKD\
HSPGPWEPEQEEPPQQESQSQPQPQPQSDP\
>gi|31543236|ref|NP_033608.2| mitogen activated protein kinase kinase kinase 12; zipper (leucine) protein kinase [Mus musculus]=:A000775:mouse\
MACLHETRTPSPSFGGFVSTLSEASMRKLDPDTSDCTPEKDLTPTQCVLRDVVPLGGQGGGGPSPSPGGEPP\
PEPFANSVLQLHEQDTGGPGGATGSPESRASRVRADEVRLQCQSGSGFLEGLFGCLRPVWTMIGKAYSTEHK\
QQQEDLWEVPFEEILDLQWVGSGAQGAVFLGRFHGEEVAVKKVRDLKETDIKHLRKLKHPNIITFKGVCTQA\
PSYCILMEFCAQGQLYEVLRAGRPVTPSLLVDWSMGIAGGMNYLHLHKIIHRDLKSPNMLITYDDVVKISDF\
GTSKELSDKSTKMSFAGTVAWMAPEVIRNEPVSEKVDIWSFGVVLWELLTGEIPYKDVDSSAIIWGVGSNSL\
HLPVPSSCPDGFKILLRQCWNSKPRNRPSFRQILLHLDIASADVLSTPQETYFKSQAEWREEVKLHFEKIKS\
EGTCLHRLEEELVMRRREELRHALDIREHYERKLERANNLYMELNALMLQLELKERELLRREQALERRCPGL\
LKSHPSRGLLHGNTMEKLIKKRNVPQKLSPHSKRPDILKTESLLPKLDAALSGVGLPGCPKGPPSPGRSRRG\
KTRHRKASAKGSCGDLPGLRAALPPHEPGGLGSPGGLGVGPSAWDACPPALRGLHHDLLLRKMSSSSPDLLS\
AALGARGRGATGGARDPGSPPPPQGDTPPSEGSAPGSTSPDSPGGAKGEPPPPVGPGEGVGLLGTGREGTAG\
RGGNRAGSQHLTPAALLYRAAVTRSQKRGISSEEEEGEVDSEVELPPSQRWPQGPNMRQSLSTFSSENPSDV\
EEGTASEPSPSGTPEVGSTNTDERPDERSDDMCSQGSEIPLDLPTSEVVPEREASSLPMQHQDGQGPNPEDS\
DCDSTELDNSNSIDALRPPASLPP\
>gi|18875340|ref|NP_573460.1| mcf.2 transforming [Mus musculus]=:A000754:mouse\
MAVANPPRGKMRFRRNAASFPGSLHLVLVLRPTSFLQRTFTDIGFRFSQEDFMLKLPVVMLSSVSDLLTYID\
DKQLTPELGGTLQYCHSEWIIFRNAIEKFAVTVKEMAQMLQSFGTELAETELPQDILSIEEILAGRAERYHL\
LKNDLTAVTKEGKVLLMNLQVPATEETVSSSLECTQHINGDWQTIKKLLAQVHDMETAFDGFWEKHQLKMEQ\
YLQLWKFEQDFQEAVTQVEFLLSQQRELGDITGNLAQVKQRLKKLEILDDKSQELLTKARIVILRGHKLASN\
HHYALDLICQRCNELRYLSDILVNEIRTKRVQLSRTFKVHRLLQQARQCCDQGECLLASQGMDKFQTKEDAQ\
KALQDVDNFLQMAMPFINYDIESLQYEFDVLLSPELKAQMQNIQLKLENIRSAFQNQQAGCKSLKEVPEGAF\
QNLVPASENVMRSRMIFFSPKHVKKSWRQIRAQSNVKVEAVEDSQEKNSDQSPKLDNSLDILKNHVLDELIQ\
TERAYVRELFTVLLGYRSEMDNPQMFDLMPPLLRNKKDVLFGNMAEIYEFHNNIFMSRLEDCSDAPERVGPC\
FLERKDDFQMYAKYCQNKPRSELIWRKYSECAFFQECQRKLKHRLGLDSYLLKPVQRITKYQLLLKELLKYS\
KEGEGTTKLKEALDSMLELLKSVNDSMHQTAINAYVGNINELGKMVLQGSFNVWLGHRKGATKMKDFARFKP\
MQRHLFLYEKAVMFCKRRFESGEGADRYPSYSFKHCLKMEDVGITEHVKGDNRKFEIRYSEKEEIYIVQAPN\
VDVKMLWLKEIRKILVQQKELMTAKTQQDQALDQDQLFPQQQNAELCKSSPFCVCEETLFNATEAGAEVEQA\
GALIKVREAAVLAQAEASSAAWNGMLPSAEGAAAIAEHSYNYFSSNNDHGEDRTQMRHMSEVTF\
>gi|18875344|ref|NP_573462.1| sodium channel, voltage-gated, type IV, alpha polypeptide [Mus musculus]=:A001613:mouse\
MASSSLPTLVPPGPHCLRPFTPESLAAIEQRAMEEEARLQRNKQMEIEEPERKPRSDLEAGKNLPLIYGDPP\
PEVIGVPLEDLDPYYSDKKTFIVLNKGKAIFRFSATPALYMLSPFSIVRRVAIKVLIHALFSMFIMITILTN\
CVFMTMSNPPSWSKDVEYTFTGIYTFESLIKMLARGFCIDDFTFLRDPWNWLDFSVITMAYVTEFVDLGNIS\
ALRTFRVLRALKTITVIPGLKTIVGALIQSVKKLSDVMILTVFCLSVFALVGLQLFMGNLRQKCVRWPPPMN\
DTNTTWYGNDTWYGNDTWYGNDTWYGNDTWNSQESWVSNSTFDWEAYINDEGNFYFLEGSNDALLCGNSSDA\
GHCPEGYECMKAGRNPNYGYTSYDTFSWAFLALFRLMTQDYWENLFQLTLRAAGKTYMIFFVVIIFLGSFYL\
INLILAVVAMAYAEQNEATLAEDQEKEEEFQQMLEKFKKHQEELEKAKAAQALEGGEEADGDPTHSKDCNGS\
LDTSGEKGPPRPSCSAESAISDAMEELEEAHQKCPPWWYKCAHKVLIWNCCAPWVKFKHIILLIVMDPFVDL\
GITICIVLNTLFMAMEHYPMTEHFDNVLSVGNLVFTGIFTAEMVLKLIAMDPYEYFQQGWNIFDSFIVTLSL\
VELGLANVQGLSVLRSFRLLRVFKLAKSWPTLNMLIKIIGNSVGALGNLTLVLAIIVFIFAVVGMQLFGKSY\
KECVCKIASDCSLPRWHMHDFFHSFLIVFRILCGEWIETMWDCMEVAGQAMCLTVFLMVMVIGNLVVLNLFL\
ALLLSSFSADSLAASDEDGEMNNLQIAIGRIKWGIAFAKTFLLGLLHGKILSLKDIMLSLGEPGGAGENGES\
PPEDEKKEPPPEDGNKELKDNHILNHVGLTDGPRSSIEMDHLNFINNPYLTIHVPIASEESDLEMPTEEETD\
TFSEPEDIKKPLQPLYDGNSSVCSTADYKPPEEDPEEQAEENPEGELPEECFTEACVKRCPCLYVDISQGRG\
KMWWTLRRACFKIVEHNWFETFIVFMILLSSGALAFEDIYIEQRRVIRTILEYADKVFTYIFILEMLLKWVA\
YGFKVYFTNAWCWLDFLIVDVSIISLVANWLGYSELGPIKSLRTLRALRPLRALSRFEGMRVVVNALLGAIP\
SIMNVLLVCLIFWLIFSIMGVNLFAGKFYYCINTTTSERFDISVVNNKSECESLMYTGQVRWMNVKVNYDNV\
GLGYLSLLQVATFKGWMDIMYAAVDSREKEEQPDYEVNLYMYLYFVIFIIFGSFFTLNLFIGVIIDNFNQQK\
KKFGGKDIFMTEEQKKYYNAMKKLGSKKPQKPIPRPQNKIQGMVYDFVTKQVFDISIMILICLNMVTMMVET\
DDQSQLKVDILYNINMVFIIVFTGECVLKMFALRHYYFTIGWNIFDFVVVILSIVGLALSDLIQKYFVSPTL\
FRVIRLARIGRVLRLIRGAKGIRTLLFALMMSLPALFNIGLLLFLVMFIYSIFGMSNFAYVKKESGIDDMFN\
FETFGNSIICLFEITTSAGWDGLLNPILNSGPPDCDPTLENPGTNIKGDCGNPSIGICFFCSYIIISFLIVV\
NMYIAIILENFNVATEESSEPLCEDDFEMFYETWEKFDPDATQFIDYSRLSDFVDTLQEPLKIAKPNKIKLI\
TLDLPMVPGDKIHCLDILFALTKEVLGDSGEMDALKQTMEEKFMAANPSKVSYEPITTTLKRKQEEVCAIKI\
QRAYRRHLLQRSVKQASYMYRHSQEGNGDGAPEKEGLLANTMNKMYGSEKEDNGVQSQGEKEKDSTEDAGPT\
TEVTAPSSSDTALTPPPPSPPPPSSPPQGQTVRPGVKESLV\
>gi|7110597|ref|NP_032119.1| GATA binding protein 5; GATA-binding protein 5 [Mus musculus]=:A001030:mouse\
MYQSLALAQSPGQGTYADSGAFLHSSGTGSPVFVAPTRMPSMLPYLPSCEPGSQAPALAAHSSWTQTVAADS\
SAFGSGSPHPPAAHPPGATTFPFAHSPPGSGSGGSAGVRDGGAFQGALLAREQYPTPLGRPMGASYPTTYPA\
YMSSDVAPSWTSGAFDSSILHGLQARPGGLPGRRTSFVPDFLEEFPGEGRECVNCGALSTPLWRRDGTGHYL\
CNACGLYHKMNGVNRPLVRPQKRLSSSRRSGLCCSNCHTATTTLWRRNSEGEPVCNACGLYMKLHGVPRPLA\
MKKESIQTRKRKPENPAKIKGSSGSTANTTASSPTLLNSESSATTLKAESSLASPVCAGPTITSQASSPADE\
SLASSHLEFKFEPEDFAFTSSSMSPQAGLSGVLRQETWCALALA\
>gi|10181220|ref|NP_065599.1| potassium voltage-gated channel, Isk-related subfamily, gene 3; minK-related peptide 2 [Mus musculus]=:A001541:mouse\
METSNGTETWYMSLHAVLKALNTTLHSHLLCRPGPGPGPDNQTEDRRASLPGRNDNSYMYILFVMFLFAVTV\
GSLILGYTRSRKVDKRSDPYHVYIKNRVSMI\
>gi|21312161|ref|NP_082668.1| RIKEN cDNA 2900026H06 [Mus musculus]=:A001865:mouse\
MKCFSRYLPYIFRPPNTILSSSCHTEADIISTVEFNHTGELLATGDKGGRVVIFQREQESKNQVHRRGEYNV\
YSTFQSHEPEFDYLKSLEIEEKINKIRWLPQQNAAYFLLSTNDKTVKLWKVSERDKRPEGYNLKDEEGRLRD\
PATITTLRVPVLRPMDLMVEATPRRVFANAHTYHINSISVNSDYETYMSADDLRINLWNFEITNQSFNIVDI\
KPANMEELTEVITAAEFHPHHCNTFVYSSSKGTIRLCDMRASALCDRHTKFFEEPEDPSNRSFFSEIISSIS\
DVKFSHSGRYIMTRDYLTVKVWDLNMENRPIETYQVHDYLRSKLCSLYENDCIFDKFECVWNGSDSVIMTGS\
YNNFFRMFDRNTKRDVTLEASRENSKPRAILKPRKVCVGGKRRKDEISVDSLDFSKKILHTAWHPSENIIAV\
AATNNLYIFQDKVN";
